# what language the build will be configured for
language: generic

os:
    - osx
# specify what versions of python will be used
# note that all of the versions listed will be tried
matrix:
    include:
        - python: 3.6
        - python: 3.7

# what branches should be evaluated
branches:
    except:
# Check ALL? Decide as work progresses...

# commands to prepare the conda install - download the latest conda
# and install it and add to path
before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh 
    - bash miniconda.sh -b -p "$HOME/miniconda"
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set notify_outdated_conda false
    - conda install -c defaults -c conda-forge conda-build conda-verify codecov flake8 pep257 yapf==0.25.0
    - if [[ "$CONDA_CANARY" == "yes" ]]; then conda install -c conda-canary conda; fi
    - conda info -a
    - export LANG=en_US.UTF-8
    - export COVERAGE_DIR=":$HOME/htmlcov"
    - printenv | sort

# list of commands to run to setup the environment
install:
    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
    - conda activate test-environment
    - conda install --yes coverage coveralls flake8

# a list of commands to run before the main script
before_script:
    - flake8 hardy

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
